# Generated by Django 2.0.8 on 2018-09-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country name')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='City name')),
                ('description', models.TextField(blank=True, verbose_name='City name')),
            ],
        ),
    ]
