# Generated by Django 2.0.8 on 2018-09-25 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Man'), (2, 'Woman')], null=True),
        ),
    ]
